### PR TITLE
Adapt database extensions creations

### PR DESCRIPTION
**Pull request by sjib**
take over adaption from tww to tdh https://github.com/teksi/wastewater/pull/248/files#diff-22392b069888f310c69ad00ccde979089a36916128b7edd43a6a90818301c69c

### CODE REVIEW

**Comment by ponceta** [comment]
@sjib CI should now fail successfully due to legitimate reasons!

**Comment by ponceta** [comment]
- [ ] `psql: error: /src/datamodel/scripts/../12_0_roles.sql: No such file or directory`

**Comment by sjib** [comment]
@ponceta Great. 
May be we could add the keyword "wastewater" to scripts/banned-words.sh to avoid spelling mistakes from copy / paste.
Do you know how to add an additional keywords?

**Comment by ponceta** [comment]
> @ponceta Great. May be we could add the keyword "wastewater" to scripts/banned-words.sh to avoid spelling mistakes from copy / paste. Do you know how to add an additional keywords?

See https://github.com/teksi/district_heating/pull/24/commits/0fd317055625c1fb6f51f3ee34ec7b8cee96fe88

**Review by ponceta — APPROVED** [review]

**Pull request merged**
