### PR TITLE
2024 10 28 update tdh protection tube create code

### PR DESCRIPTION
**Pull request by sjib**

### CODE REVIEW

**Comment by sjib** [comment]
@jpdupuy To which class should I add a reference for the protection_tube class?

- [ ] pipe_section or
- [ ] trench

[Class diagramm](https://github.com/teksi/district_heating/issues/10#issuecomment-2117459433)

**Comment by jpdupuy** [comment]
@sjib to pipe_section

**Comment by ponceta** [comment]
Ok for pipe_section as it is now a minimal implementation. What would be the equivalent class of ww channel in district heating?

**Review by ponceta — APPROVED** [review]

**Comment by ponceta** [comment]
@sjib waiting for the fk_pipe_section before merging this.

**Pull request merged**
